---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ssstp"
  namespace: "default"
  labels:
    app: "ssstp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ssstp"
  template:
    metadata:
      labels:
        app: "ssstp"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:7d991c9a4598f37ab64a8ce20768052377cda3b85193ca0a28b1357eec030730"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ssstp-hpa-egdi"
  namespace: "default"
  labels:
    app: "ssstp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ssstp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
