---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ovsdb-sirishateam-4"
  namespace: "default"
  labels:
    app: "ovsdb-sirishateam-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ovsdb-sirishateam-4"
  template:
    metadata:
      labels:
        app: "ovsdb-sirishateam-4"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:3d74ab586ae75cb99c7d45499363b7c5353133b4d5cf97acc2c40e13bf397e5b"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ovsdb-sirishateam-4-hpa-mjch"
  namespace: "default"
  labels:
    app: "ovsdb-sirishateam-4"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ovsdb-sirishateam-4"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
