---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "onlinevegetablesale"
  namespace: "default"
  labels:
    app: "onlinevegetablesale"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "onlinevegetablesale"
  template:
    metadata:
      labels:
        app: "onlinevegetablesale"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:ac1ec1cbaebba9a3d093c92ee778c1354195897be6edc936816634fd303fc2df"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "onlinevegetablesale-hpa-3t6a"
  namespace: "default"
  labels:
    app: "onlinevegetablesale"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "onlinevegetablesale"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
