---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "siri-onlinevegetabledb"
  namespace: "default"
  labels:
    app: "siri-onlinevegetabledb"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "siri-onlinevegetabledb"
  template:
    metadata:
      labels:
        app: "siri-onlinevegetabledb"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:89285647944e5a49cfc08ef11adc70fc1ab405f9f43b0c2208319e3622650ae4"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "siri-onlinevegetabledb-hpa-jcuw"
  namespace: "default"
  labels:
    app: "siri-onlinevegetabledb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "siri-onlinevegetabledb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
