---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sirisha-ovsdb"
  namespace: "default"
  labels:
    app: "sirisha-ovsdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sirisha-ovsdb"
  template:
    metadata:
      labels:
        app: "sirisha-ovsdb"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:f370d1b56b01c07562da2c43be22dcced13c8e6056ae1fb0ce9e40651ebf8fe6"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sirisha-ovsdb-hpa-jivn"
  namespace: "default"
  labels:
    app: "sirisha-ovsdb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sirisha-ovsdb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
