---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "onlinevegetablesale-db"
  namespace: "default"
  labels:
    app: "onlinevegetablesale-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "onlinevegetablesale-db"
  template:
    metadata:
      labels:
        app: "onlinevegetablesale-db"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:672bba9b32ad94bde4fe2f2cad6f661826f4362aec483f60c9cf1e848d8c7956"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "onlinevegetablesale-db-hpa-vatn"
  namespace: "default"
  labels:
    app: "onlinevegetablesale-db"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "onlinevegetablesale-db"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
