---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-sptss-ovs"
  namespace: "default"
  labels:
    app: "nginx-sptss-ovs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-sptss-ovs"
  template:
    metadata:
      labels:
        app: "nginx-sptss-ovs"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:2930697f742a8351588e985040df540ecebe9191cdb60364324045dbbce1b1ae"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-sptss-ovs-hpa-3mvk"
  namespace: "default"
  labels:
    app: "nginx-sptss-ovs"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-sptss-ovs"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
