---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ovegtab-team4-sirisha"
  namespace: "default"
  labels:
    app: "ovegtab-team4-sirisha"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ovegtab-team4-sirisha"
  template:
    metadata:
      labels:
        app: "ovegtab-team4-sirisha"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:4c6b1ee5e7e5459ccc221bcf3e9c0ee33f1994957dd2e09d059540562d8913cd"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ovegtab-team4-sirisha-hpa-qorx"
  namespace: "default"
  labels:
    app: "ovegtab-team4-sirisha"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ovegtab-team4-sirisha"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
