---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "team4-ssstp-ovs"
  namespace: "default"
  labels:
    app: "team4-ssstp-ovs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "team4-ssstp-ovs"
  template:
    metadata:
      labels:
        app: "team4-ssstp-ovs"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:e61389459fab14797facba5142b80db23c17610d5ab793399d9fa1dd72a142f8"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "team4-ssstp-ovs-hpa-uqce"
  namespace: "default"
  labels:
    app: "team4-ssstp-ovs"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "team4-ssstp-ovs"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
