---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "siriladdu-ovsdb"
  namespace: "default"
  labels:
    app: "siriladdu-ovsdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "siriladdu-ovsdb"
  template:
    metadata:
      labels:
        app: "siriladdu-ovsdb"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:36b852370eb3d1b9fcfb55531e79341e3deef364a5b52615afc4d246776bc8a7"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "siriladdu-ovsdb-hpa-h7xu"
  namespace: "default"
  labels:
    app: "siriladdu-ovsdb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "siriladdu-ovsdb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
