---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "m3-ovsdb"
  namespace: "default"
  labels:
    app: "m3-ovsdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "m3-ovsdb"
  template:
    metadata:
      labels:
        app: "m3-ovsdb"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:88ccfe9a00309f8d43b54eb245d4c9f6bcd0488f0b580587d12fc6a02022c4c9"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "m3-ovsdb-hpa-gqv9"
  namespace: "default"
  labels:
    app: "m3-ovsdb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "m3-ovsdb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
