---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-45"
  namespace: "default"
  labels:
    app: "nginx-45"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-45"
  template:
    metadata:
      labels:
        app: "nginx-45"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:f6e581b708a6bf2ef56fc75abbc73b3fa49ea355a638f7c2571475891e256ab1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-45-hpa-69yb"
  namespace: "default"
  labels:
    app: "nginx-45"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-45"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
