---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sirisha-team4-ovs"
  namespace: "default"
  labels:
    app: "sirisha-team4-ovs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sirisha-team4-ovs"
  template:
    metadata:
      labels:
        app: "sirisha-team4-ovs"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:f415a05f0af46dd78ea500771d155b7e08d903ecea2076e3c01de48b34a4daad"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sirisha-team4-ovs-hpa-eexe"
  namespace: "default"
  labels:
    app: "sirisha-team4-ovs"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sirisha-team4-ovs"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
