---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "team4-db"
  namespace: "default"
  labels:
    app: "team4-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "team4-db"
  template:
    metadata:
      labels:
        app: "team4-db"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:fea760459af07e0713fb813872f813855d5f6fe415889c1138bae681b2d4b60a"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "team4-db-hpa-am7d"
  namespace: "default"
  labels:
    app: "team4-db"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "team4-db"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
