---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-sirisha-ovs"
  namespace: "default"
  labels:
    app: "nginx-sirisha-ovs"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-sirisha-ovs"
  template:
    metadata:
      labels:
        app: "nginx-sirisha-ovs"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:0cef5ae7eb21c43a5db488b2f57c4e458d7328db75e30d889987cb649399f060"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-sirisha-ovs-hpa-b79y"
  namespace: "default"
  labels:
    app: "nginx-sirisha-ovs"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-sirisha-ovs"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
