---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "siribb-ovs"
  namespace: "default"
  labels:
    app: "siribb-ovs"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "siribb-ovs"
  template:
    metadata:
      labels:
        app: "siribb-ovs"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:0b61692b73ad0fdf690317818555f94a25a06d3a3a429cbb48b8e62a73e9fe24"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "siribb-ovs-hpa-vrjm"
  namespace: "default"
  labels:
    app: "siribb-ovs"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "siribb-ovs"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
