---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "onlinevegetabledb"
  namespace: "default"
  labels:
    app: "onlinevegetabledb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "onlinevegetabledb"
  template:
    metadata:
      labels:
        app: "onlinevegetabledb"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:a7f83327ad7a990a63b6e544514b80538a6f3f41996e29587faf53a9739d70f6"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "onlinevegetabledb-hpa-5t4h"
  namespace: "default"
  labels:
    app: "onlinevegetabledb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "onlinevegetabledb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

