---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sirispringappdb"
  namespace: "default"
  labels:
    app: "sirispringappdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "sirispringappdb"
  template:
    metadata:
      labels:
        app: "sirispringappdb"
    spec:
      containers:
      - name: "myproject-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/sirishabb/myproject@sha256:d11062206dd57449e980b09931fdbaa0e1eefcf240325866910011812bd78a4c"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sirispringappdb-hpa-fape"
  namespace: "default"
  labels:
    app: "sirispringappdb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sirispringappdb"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
